"""initial migration

Revision ID: 3715ecb7ed3a
Revises: 
Create Date: 2026-04-02 19:44:10.963050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3715ecb7ed3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('client_secret_hash', sa.String(length=255), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id'),
    sa.UniqueConstraint('organisation_name')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource'), 'audit_logs', ['resource'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('gdpr_deletion_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('resident_id', sa.String(), nullable=False),
    sa.Column('certificate_id', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_by', sa.String(), nullable=False),
    sa.Column('evidence_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gdpr_deletion_logs_certificate_id'), 'gdpr_deletion_logs', ['certificate_id'], unique=True)
    op.create_index(op.f('ix_gdpr_deletion_logs_resident_id'), 'gdpr_deletion_logs', ['resident_id'], unique=False)
    op.create_index(op.f('ix_gdpr_deletion_logs_tenant_id'), 'gdpr_deletion_logs', ['tenant_id'], unique=False)
    op.create_table('residents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('internal_reference', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('diagnosis_codes', sa.JSON(), nullable=False),
    sa.Column('risk_profile', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('baseline_window_days', sa.Integer(), nullable=False),
    sa.Column('baseline_status', sa.String(length=30), nullable=False),
    sa.Column('baseline_data', sa.JSON(), nullable=True),
    sa.Column('baseline_last_calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('baseline_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('baseline_reset_reason', sa.String(length=50), nullable=True),
    sa.Column('total_observations', sa.Integer(), nullable=False),
    sa.Column('last_observation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'internal_reference')
    )
    op.create_index(op.f('ix_residents_tenant_id'), 'residents', ['tenant_id'], unique=False)
    op.create_table('webhooks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('min_tier', sa.String(length=4), nullable=False),
    sa.Column('signing_secret', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooks_tenant_id'), 'webhooks', ['tenant_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resident_id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('tier', sa.String(length=4), nullable=False),
    sa.Column('tier_label', sa.String(length=20), nullable=False),
    sa.Column('drift_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('historical_context', sa.JSON(), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_by', sa.String(length=128), nullable=True),
    sa.Column('dismiss_reason', sa.String(length=300), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=128), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_resident_dismissed', 'alerts', ['resident_id', 'dismissed'], unique=False)
    op.create_index(op.f('ix_alerts_tenant_id'), 'alerts', ['tenant_id'], unique=False)
    op.create_index('ix_alerts_tenant_tier', 'alerts', ['tenant_id', 'tier'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resident_id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('observer_id', sa.String(length=64), nullable=True),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('drift_score', sa.Float(), nullable=True),
    sa.Column('drift_triggered', sa.Boolean(), nullable=True),
    sa.Column('signals_flagged', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_observations_resident_observed_at', 'observations', ['resident_id', 'observed_at'], unique=False)
    op.create_index(op.f('ix_observations_tenant_id'), 'observations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observations_tenant_id'), table_name='observations')
    op.drop_index('ix_observations_resident_observed_at', table_name='observations')
    op.drop_table('observations')
    op.drop_index('ix_alerts_tenant_tier', table_name='alerts')
    op.drop_index(op.f('ix_alerts_tenant_id'), table_name='alerts')
    op.drop_index('ix_alerts_resident_dismissed', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_webhooks_tenant_id'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_residents_tenant_id'), table_name='residents')
    op.drop_table('residents')
    op.drop_index(op.f('ix_gdpr_deletion_logs_tenant_id'), table_name='gdpr_deletion_logs')
    op.drop_index(op.f('ix_gdpr_deletion_logs_resident_id'), table_name='gdpr_deletion_logs')
    op.drop_index(op.f('ix_gdpr_deletion_logs_certificate_id'), table_name='gdpr_deletion_logs')
    op.drop_table('gdpr_deletion_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('tenants')
    # ### end Alembic commands ###
